/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.spacesystem.telas;

import br.com.spacesystem.dao.Conexao;
import java.sql.*;

/**
 *
 * @author alexf
 */
public class frmLogin extends javax.swing.JFrame {
    
    Connection conexao=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        conexao=Conexao.conector();
        
        
        if(conexao!=null){
            lbl_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacesystem/icones/1485552443_accept-database.png")));
            lbl_status.setText(" Servidor Conectado");
        }else{
            lbl_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacesystem/icones/1485552463_remove-from-database.png")));
            lbl_status.setText(" Erro na Conexão com Servidor!");
        }
             
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lb_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 90, 46, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 130, 38, 20);

        txt_usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(150, 90, 150, 30);
        getContentPane().add(txt_senha);
        txt_senha.setBounds(150, 130, 150, 30);

        btn_login.setBackground(new java.awt.Color(102, 204, 255));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacesystem/icones/1485562089_Login_in.png"))); // NOI18N
        btn_login.setText("    Login");
        getContentPane().add(btn_login);
        btn_login.setBounds(150, 170, 150, 40);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel3.setText("SpaceSystem - Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 30, 260, 30);

        lbl_status.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacesystem/icones/1485552463_remove-from-database.png"))); // NOI18N
        getContentPane().add(lbl_status);
        lbl_status.setBounds(10, 200, 240, 40);

        lb_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/spacesystem/imagens/login - imagem fundo.png"))); // NOI18N
        getContentPane().add(lb_fundo);
        lb_fundo.setBounds(0, 0, 440, 240);

        setSize(new java.awt.Dimension(416, 270));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_fundo;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
